name: vaa1_compatible
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=2.2
  - pandas=2.3
  - scipy=1.15
  - matplotlib=3.10
  - pillow=12.0
  - opencv=4.12
  - ffmpeg
  - pytorch::pytorch=2.9
  - pytorch::torchvision=0.24
  - pytorch::torchaudio=2.9
  - transformers=4.57
  - spacy=3.8
  - ultralytics=8.3
  - openai-whisper

  - pip:
      - aiofiles==25.1.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - blis==1.3.2
      - catalogue==2.0.10
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpathlib==0.23.0
      - colorama==0.4.6
      - confection==0.1.5
      - contourpy==1.3.2
      - cycler==0.12.1
      - cymem==2.0.13
      - easyocr==1.7.2
      - exceptiongroup==1.3.1
      - fastapi==0.121.3
      - ffmpeg-python==0.2.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - future==1.0.0
      - h11==0.16.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - murmurhash==1.0.15
      - networkx==3.4.2
      - ninja==1.13.0
      - numba==0.62.1
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - polars==1.35.1
      - polars-runtime-32==1.35.1
      - preshed==3.0.11
      - psutil==7.1.3
      - pyclipper==1.3.0.post6
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - shapely==2.1.2
      - six==1.17.0
      - smart-open==7.5.0
      - sniffio==1.3.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - starlette==0.50.0
      - sympy==1.14.0
      - thinc==8.3.9
      - tifffile==2025.5.10
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ultralytics-thop==2.0.18
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wasabi==1.1.3
      - weasel==0.4.3
      - whisper==1.1.10
      - wrapt==2.0.1